# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NGXS STORAGE PLUGIN EXTENSION CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
    build-and-deploy:
        if: "!contains(github.event.head_commit.message , 'ci skip')"

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   uses: actions/cache@v2
                with:
                    path: node_modules
                    key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: ${{ runner.os }}-yarn

            -   name: Install dependencies
                run: |
                    yarn install --frozen-lockfile --non-interactive

            -   name: Build libraries
                run: |
                    yarn build:lib

            -   name: Run lint
                run: |
                    yarn lint

            -   name: Run tests
                run: |
                    yarn test --coverage
                    yarn test:types

            -   name: Build integration app
                run: yarn build:app
